/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class Lane {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Lane(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Lane obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_Lane(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static StringVector getIDList() {
    return new StringVector(libsumoJNI.Lane_getIDList(), true);
  }

  public static int getIDCount() {
    return libsumoJNI.Lane_getIDCount();
  }

  public static int getLinkNumber(String laneID) {
    return libsumoJNI.Lane_getLinkNumber(laneID);
  }

  public static String getEdgeID(String laneID) {
    return libsumoJNI.Lane_getEdgeID(laneID);
  }

  public static double getLength(String laneID) {
    return libsumoJNI.Lane_getLength(laneID);
  }

  public static double getMaxSpeed(String laneID) {
    return libsumoJNI.Lane_getMaxSpeed(laneID);
  }

  public static StringVector getAllowed(String laneID) {
    return new StringVector(libsumoJNI.Lane_getAllowed(laneID), true);
  }

  public static StringVector getDisallowed(String laneID) {
    return new StringVector(libsumoJNI.Lane_getDisallowed(laneID), true);
  }

  public static TraCIConnectionVector getLinks(String laneID) {
    return new TraCIConnectionVector(libsumoJNI.Lane_getLinks(laneID), true);
  }

  public static SWIGTYPE_p_std__vectorT_libsumo__TraCIPosition_t getShape(String laneID) {
    return new SWIGTYPE_p_std__vectorT_libsumo__TraCIPosition_t(libsumoJNI.Lane_getShape(laneID), true);
  }

  public static double getWidth(String laneID) {
    return libsumoJNI.Lane_getWidth(laneID);
  }

  public static double getCO2Emission(String laneID) {
    return libsumoJNI.Lane_getCO2Emission(laneID);
  }

  public static double getCOEmission(String laneID) {
    return libsumoJNI.Lane_getCOEmission(laneID);
  }

  public static double getHCEmission(String laneID) {
    return libsumoJNI.Lane_getHCEmission(laneID);
  }

  public static double getPMxEmission(String laneID) {
    return libsumoJNI.Lane_getPMxEmission(laneID);
  }

  public static double getNOxEmission(String laneID) {
    return libsumoJNI.Lane_getNOxEmission(laneID);
  }

  public static double getFuelConsumption(String laneID) {
    return libsumoJNI.Lane_getFuelConsumption(laneID);
  }

  public static double getNoiseEmission(String laneID) {
    return libsumoJNI.Lane_getNoiseEmission(laneID);
  }

  public static double getElectricityConsumption(String laneID) {
    return libsumoJNI.Lane_getElectricityConsumption(laneID);
  }

  public static double getLastStepMeanSpeed(String laneID) {
    return libsumoJNI.Lane_getLastStepMeanSpeed(laneID);
  }

  public static double getLastStepOccupancy(String laneID) {
    return libsumoJNI.Lane_getLastStepOccupancy(laneID);
  }

  public static double getLastStepLength(String laneID) {
    return libsumoJNI.Lane_getLastStepLength(laneID);
  }

  public static double getWaitingTime(String laneID) {
    return libsumoJNI.Lane_getWaitingTime(laneID);
  }

  public static double getTraveltime(String laneID) {
    return libsumoJNI.Lane_getTraveltime(laneID);
  }

  public static int getLastStepVehicleNumber(String laneID) {
    return libsumoJNI.Lane_getLastStepVehicleNumber(laneID);
  }

  public static int getLastStepHaltingNumber(String laneID) {
    return libsumoJNI.Lane_getLastStepHaltingNumber(laneID);
  }

  public static StringVector getLastStepVehicleIDs(String laneID) {
    return new StringVector(libsumoJNI.Lane_getLastStepVehicleIDs(laneID), true);
  }

  public static StringVector getFoes(String laneID, String toLaneID) {
    return new StringVector(libsumoJNI.Lane_getFoes(laneID, toLaneID), true);
  }

  public static StringVector getInternalFoes(String laneID) {
    return new StringVector(libsumoJNI.Lane_getInternalFoes(laneID), true);
  }

  public static void setAllowed(String laneID, StringVector allowedClasses) {
    libsumoJNI.Lane_setAllowed(laneID, StringVector.getCPtr(allowedClasses), allowedClasses);
  }

  public static void setDisallowed(String laneID, StringVector disallowedClasses) {
    libsumoJNI.Lane_setDisallowed(laneID, StringVector.getCPtr(disallowedClasses), disallowedClasses);
  }

  public static void setMaxSpeed(String laneID, double speed) {
    libsumoJNI.Lane_setMaxSpeed(laneID, speed);
  }

  public static void setLength(String laneID, double length) {
    libsumoJNI.Lane_setLength(laneID, length);
  }

  public static String getParameter(String laneID, String param) {
    return libsumoJNI.Lane_getParameter(laneID, param);
  }

  public static void setParameter(String routeID, String key, String value) {
    libsumoJNI.Lane_setParameter(routeID, key, value);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.Lane_subscribe__SWIG_0(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.Lane_subscribe__SWIG_1(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.Lane_subscribe__SWIG_2(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribe(String objID) {
    libsumoJNI.Lane_subscribe__SWIG_3(objID);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.Lane_subscribeContext__SWIG_0(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.Lane_subscribeContext__SWIG_1(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.Lane_subscribeContext__SWIG_2(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribeContext(String objID, int domain, double range) {
    libsumoJNI.Lane_subscribeContext__SWIG_3(objID, domain, range);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getAllSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.Lane_getAllSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t getSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t(libsumoJNI.Lane_getSubscriptionResults(objID), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t getAllContextSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t(libsumoJNI.Lane_getAllContextSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getContextSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.Lane_getContextSubscriptionResults(objID), true);
  }

  public static void storeShape(String id, SWIGTYPE_p_PositionVector shape) {
    libsumoJNI.Lane_storeShape(id, SWIGTYPE_p_PositionVector.getCPtr(shape));
  }

  public static SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t makeWrapper() {
    return new SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t(libsumoJNI.Lane_makeWrapper(), true);
  }

  public static boolean handleVariable(String objID, int variable, SWIGTYPE_p_libsumo__VariableWrapper wrapper) {
    return libsumoJNI.Lane_handleVariable(objID, variable, SWIGTYPE_p_libsumo__VariableWrapper.getCPtr(wrapper));
  }

}
