/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public interface libsumoConstants {
  public final static int INVALID_DOUBLE_VALUE = libsumoJNI.INVALID_DOUBLE_VALUE_get();
}
