/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class Person {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Person(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Person obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_Person(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static StringVector getIDList() {
    return new StringVector(libsumoJNI.Person_getIDList(), true);
  }

  public static int getIDCount() {
    return libsumoJNI.Person_getIDCount();
  }

  public static double getSpeed(String personID) {
    return libsumoJNI.Person_getSpeed(personID);
  }

  public static TraCIPosition getPosition(String personID, boolean includeZ) {
    return new TraCIPosition(libsumoJNI.Person_getPosition__SWIG_0(personID, includeZ), true);
  }

  public static TraCIPosition getPosition(String personID) {
    return new TraCIPosition(libsumoJNI.Person_getPosition__SWIG_1(personID), true);
  }

  public static String getRoadID(String personID) {
    return libsumoJNI.Person_getRoadID(personID);
  }

  public static String getTypeID(String personID) {
    return libsumoJNI.Person_getTypeID(personID);
  }

  public static double getWaitingTime(String personID) {
    return libsumoJNI.Person_getWaitingTime(personID);
  }

  public static String getNextEdge(String personID) {
    return libsumoJNI.Person_getNextEdge(personID);
  }

  public static String getVehicle(String personID) {
    return libsumoJNI.Person_getVehicle(personID);
  }

  public static int getRemainingStages(String personID) {
    return libsumoJNI.Person_getRemainingStages(personID);
  }

  public static int getStage(String personID, int nextStageIndex) {
    return libsumoJNI.Person_getStage__SWIG_0(personID, nextStageIndex);
  }

  public static int getStage(String personID) {
    return libsumoJNI.Person_getStage__SWIG_1(personID);
  }

  public static StringVector getEdges(String personID, int nextStageIndex) {
    return new StringVector(libsumoJNI.Person_getEdges__SWIG_0(personID, nextStageIndex), true);
  }

  public static StringVector getEdges(String personID) {
    return new StringVector(libsumoJNI.Person_getEdges__SWIG_1(personID), true);
  }

  public static String getParameter(String routeID, String param) {
    return libsumoJNI.Person_getParameter(routeID, param);
  }

  public static double getAngle(String personID) {
    return libsumoJNI.Person_getAngle(personID);
  }

  public static double getLanePosition(String personID) {
    return libsumoJNI.Person_getLanePosition(personID);
  }

  public static double getLength(String typeID) {
    return libsumoJNI.Person_getLength(typeID);
  }

  public static double getMaxSpeed(String typeID) {
    return libsumoJNI.Person_getMaxSpeed(typeID);
  }

  public static double getActionStepLength(String typeID) {
    return libsumoJNI.Person_getActionStepLength(typeID);
  }

  public static double getSpeedFactor(String typeID) {
    return libsumoJNI.Person_getSpeedFactor(typeID);
  }

  public static double getSpeedDeviation(String typeID) {
    return libsumoJNI.Person_getSpeedDeviation(typeID);
  }

  public static double getAccel(String typeID) {
    return libsumoJNI.Person_getAccel(typeID);
  }

  public static double getDecel(String typeID) {
    return libsumoJNI.Person_getDecel(typeID);
  }

  public static double getEmergencyDecel(String typeID) {
    return libsumoJNI.Person_getEmergencyDecel(typeID);
  }

  public static double getApparentDecel(String typeID) {
    return libsumoJNI.Person_getApparentDecel(typeID);
  }

  public static double getImperfection(String typeID) {
    return libsumoJNI.Person_getImperfection(typeID);
  }

  public static double getTau(String typeID) {
    return libsumoJNI.Person_getTau(typeID);
  }

  public static String getVehicleClass(String typeID) {
    return libsumoJNI.Person_getVehicleClass(typeID);
  }

  public static String getEmissionClass(String typeID) {
    return libsumoJNI.Person_getEmissionClass(typeID);
  }

  public static String getShapeClass(String typeID) {
    return libsumoJNI.Person_getShapeClass(typeID);
  }

  public static double getMinGap(String typeID) {
    return libsumoJNI.Person_getMinGap(typeID);
  }

  public static double getWidth(String typeID) {
    return libsumoJNI.Person_getWidth(typeID);
  }

  public static double getHeight(String typeID) {
    return libsumoJNI.Person_getHeight(typeID);
  }

  public static TraCIColor getColor(String typeID) {
    return new TraCIColor(libsumoJNI.Person_getColor(typeID), true);
  }

  public static double getMinGapLat(String typeID) {
    return libsumoJNI.Person_getMinGapLat(typeID);
  }

  public static double getMaxSpeedLat(String typeID) {
    return libsumoJNI.Person_getMaxSpeedLat(typeID);
  }

  public static String getLateralAlignment(String typeID) {
    return libsumoJNI.Person_getLateralAlignment(typeID);
  }

  public static void add(String personID, String edgeID, double pos, double depart, String typeID) {
    libsumoJNI.Person_add__SWIG_0(personID, edgeID, pos, depart, typeID);
  }

  public static void add(String personID, String edgeID, double pos, double depart) {
    libsumoJNI.Person_add__SWIG_1(personID, edgeID, pos, depart);
  }

  public static void add(String personID, String edgeID, double pos) {
    libsumoJNI.Person_add__SWIG_2(personID, edgeID, pos);
  }

  public static void appendWaitingStage(String personID, double duration, String description, String stopID) {
    libsumoJNI.Person_appendWaitingStage__SWIG_0(personID, duration, description, stopID);
  }

  public static void appendWaitingStage(String personID, double duration, String description) {
    libsumoJNI.Person_appendWaitingStage__SWIG_1(personID, duration, description);
  }

  public static void appendWaitingStage(String personID, double duration) {
    libsumoJNI.Person_appendWaitingStage__SWIG_2(personID, duration);
  }

  public static void appendWalkingStage(String personID, StringVector edgeIDs, double arrivalPos, double duration, double speed, String stopID) {
    libsumoJNI.Person_appendWalkingStage__SWIG_0(personID, StringVector.getCPtr(edgeIDs), edgeIDs, arrivalPos, duration, speed, stopID);
  }

  public static void appendWalkingStage(String personID, StringVector edgeIDs, double arrivalPos, double duration, double speed) {
    libsumoJNI.Person_appendWalkingStage__SWIG_1(personID, StringVector.getCPtr(edgeIDs), edgeIDs, arrivalPos, duration, speed);
  }

  public static void appendWalkingStage(String personID, StringVector edgeIDs, double arrivalPos, double duration) {
    libsumoJNI.Person_appendWalkingStage__SWIG_2(personID, StringVector.getCPtr(edgeIDs), edgeIDs, arrivalPos, duration);
  }

  public static void appendWalkingStage(String personID, StringVector edgeIDs, double arrivalPos) {
    libsumoJNI.Person_appendWalkingStage__SWIG_3(personID, StringVector.getCPtr(edgeIDs), edgeIDs, arrivalPos);
  }

  public static void appendDrivingStage(String personID, String toEdge, String lines, String stopID) {
    libsumoJNI.Person_appendDrivingStage__SWIG_0(personID, toEdge, lines, stopID);
  }

  public static void appendDrivingStage(String personID, String toEdge, String lines) {
    libsumoJNI.Person_appendDrivingStage__SWIG_1(personID, toEdge, lines);
  }

  public static void removeStage(String personID, int nextStageIndex) {
    libsumoJNI.Person_removeStage(personID, nextStageIndex);
  }

  public static void rerouteTraveltime(String personID) {
    libsumoJNI.Person_rerouteTraveltime(personID);
  }

  public static void moveTo(String personID, String edgeID, double position) {
    libsumoJNI.Person_moveTo(personID, edgeID, position);
  }

  public static void moveToXY(String personID, String edgeID, double x, double y, double angle, int keepRouteFlag) {
    libsumoJNI.Person_moveToXY(personID, edgeID, x, y, angle, keepRouteFlag);
  }

  public static void setParameter(String personID, String key, String value) {
    libsumoJNI.Person_setParameter(personID, key, value);
  }

  public static void setSpeed(String personID, double speed) {
    libsumoJNI.Person_setSpeed(personID, speed);
  }

  public static void setType(String personID, String typeID) {
    libsumoJNI.Person_setType(personID, typeID);
  }

  public static void setLength(String typeID, double length) {
    libsumoJNI.Person_setLength(typeID, length);
  }

  public static void setMaxSpeed(String typeID, double speed) {
    libsumoJNI.Person_setMaxSpeed(typeID, speed);
  }

  public static void setVehicleClass(String typeID, String clazz) {
    libsumoJNI.Person_setVehicleClass(typeID, clazz);
  }

  public static void setSpeedFactor(String typeID, double factor) {
    libsumoJNI.Person_setSpeedFactor(typeID, factor);
  }

  public static void setEmissionClass(String typeID, String clazz) {
    libsumoJNI.Person_setEmissionClass(typeID, clazz);
  }

  public static void setShapeClass(String typeID, String shapeClass) {
    libsumoJNI.Person_setShapeClass(typeID, shapeClass);
  }

  public static void setWidth(String typeID, double width) {
    libsumoJNI.Person_setWidth(typeID, width);
  }

  public static void setHeight(String typeID, double height) {
    libsumoJNI.Person_setHeight(typeID, height);
  }

  public static void setMinGap(String typeID, double minGap) {
    libsumoJNI.Person_setMinGap(typeID, minGap);
  }

  public static void setAccel(String typeID, double accel) {
    libsumoJNI.Person_setAccel(typeID, accel);
  }

  public static void setDecel(String typeID, double decel) {
    libsumoJNI.Person_setDecel(typeID, decel);
  }

  public static void setEmergencyDecel(String typeID, double decel) {
    libsumoJNI.Person_setEmergencyDecel(typeID, decel);
  }

  public static void setApparentDecel(String typeID, double decel) {
    libsumoJNI.Person_setApparentDecel(typeID, decel);
  }

  public static void setImperfection(String typeID, double imperfection) {
    libsumoJNI.Person_setImperfection(typeID, imperfection);
  }

  public static void setTau(String typeID, double tau) {
    libsumoJNI.Person_setTau(typeID, tau);
  }

  public static void setColor(String typeID, TraCIColor c) {
    libsumoJNI.Person_setColor(typeID, TraCIColor.getCPtr(c), c);
  }

  public static void setMinGapLat(String typeID, double minGapLat) {
    libsumoJNI.Person_setMinGapLat(typeID, minGapLat);
  }

  public static void setMaxSpeedLat(String typeID, double speed) {
    libsumoJNI.Person_setMaxSpeedLat(typeID, speed);
  }

  public static void setLateralAlignment(String typeID, String latAlignment) {
    libsumoJNI.Person_setLateralAlignment(typeID, latAlignment);
  }

  public static void setActionStepLength(String typeID, double actionStepLength, boolean resetActionOffset) {
    libsumoJNI.Person_setActionStepLength(typeID, actionStepLength, resetActionOffset);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.Person_subscribe__SWIG_0(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.Person_subscribe__SWIG_1(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.Person_subscribe__SWIG_2(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribe(String objID) {
    libsumoJNI.Person_subscribe__SWIG_3(objID);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.Person_subscribeContext__SWIG_0(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.Person_subscribeContext__SWIG_1(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.Person_subscribeContext__SWIG_2(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribeContext(String objID, int domain, double range) {
    libsumoJNI.Person_subscribeContext__SWIG_3(objID, domain, range);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getAllSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.Person_getAllSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t getSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t(libsumoJNI.Person_getSubscriptionResults(objID), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t getAllContextSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t(libsumoJNI.Person_getAllContextSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getContextSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.Person_getContextSubscriptionResults(objID), true);
  }

  public static void storeShape(String id, SWIGTYPE_p_PositionVector shape) {
    libsumoJNI.Person_storeShape(id, SWIGTYPE_p_PositionVector.getCPtr(shape));
  }

  public static SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t makeWrapper() {
    return new SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t(libsumoJNI.Person_makeWrapper(), true);
  }

  public static boolean handleVariable(String objID, int variable, SWIGTYPE_p_libsumo__VariableWrapper wrapper) {
    return libsumoJNI.Person_handleVariable(objID, variable, SWIGTYPE_p_libsumo__VariableWrapper.getCPtr(wrapper));
  }

}
