/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class Simulation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Simulation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Simulation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_Simulation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void load(StringVector args) {
    libsumoJNI.Simulation_load(StringVector.getCPtr(args), args);
  }

  public static boolean isLoaded() {
    return libsumoJNI.Simulation_isLoaded();
  }

  public static void close() {
    libsumoJNI.Simulation_close();
  }

  public static void step(double time) {
    libsumoJNI.Simulation_step__SWIG_0(time);
  }

  public static void step() {
    libsumoJNI.Simulation_step__SWIG_1();
  }

  public static int getCurrentTime() {
    return libsumoJNI.Simulation_getCurrentTime();
  }

  public static double getTime() {
    return libsumoJNI.Simulation_getTime();
  }

  public static int getLoadedNumber() {
    return libsumoJNI.Simulation_getLoadedNumber();
  }

  public static StringVector getLoadedIDList() {
    return new StringVector(libsumoJNI.Simulation_getLoadedIDList(), true);
  }

  public static int getDepartedNumber() {
    return libsumoJNI.Simulation_getDepartedNumber();
  }

  public static StringVector getDepartedIDList() {
    return new StringVector(libsumoJNI.Simulation_getDepartedIDList(), true);
  }

  public static int getArrivedNumber() {
    return libsumoJNI.Simulation_getArrivedNumber();
  }

  public static StringVector getArrivedIDList() {
    return new StringVector(libsumoJNI.Simulation_getArrivedIDList(), true);
  }

  public static int getParkingStartingVehiclesNumber() {
    return libsumoJNI.Simulation_getParkingStartingVehiclesNumber();
  }

  public static StringVector getParkingStartingVehiclesIDList() {
    return new StringVector(libsumoJNI.Simulation_getParkingStartingVehiclesIDList(), true);
  }

  public static int getParkingEndingVehiclesNumber() {
    return libsumoJNI.Simulation_getParkingEndingVehiclesNumber();
  }

  public static StringVector getParkingEndingVehiclesIDList() {
    return new StringVector(libsumoJNI.Simulation_getParkingEndingVehiclesIDList(), true);
  }

  public static int getStopStartingVehiclesNumber() {
    return libsumoJNI.Simulation_getStopStartingVehiclesNumber();
  }

  public static StringVector getStopStartingVehiclesIDList() {
    return new StringVector(libsumoJNI.Simulation_getStopStartingVehiclesIDList(), true);
  }

  public static int getStopEndingVehiclesNumber() {
    return libsumoJNI.Simulation_getStopEndingVehiclesNumber();
  }

  public static StringVector getStopEndingVehiclesIDList() {
    return new StringVector(libsumoJNI.Simulation_getStopEndingVehiclesIDList(), true);
  }

  public static int getCollidingVehiclesNumber() {
    return libsumoJNI.Simulation_getCollidingVehiclesNumber();
  }

  public static StringVector getCollidingVehiclesIDList() {
    return new StringVector(libsumoJNI.Simulation_getCollidingVehiclesIDList(), true);
  }

  public static int getEmergencyStoppingVehiclesNumber() {
    return libsumoJNI.Simulation_getEmergencyStoppingVehiclesNumber();
  }

  public static StringVector getEmergencyStoppingVehiclesIDList() {
    return new StringVector(libsumoJNI.Simulation_getEmergencyStoppingVehiclesIDList(), true);
  }

  public static int getStartingTeleportNumber() {
    return libsumoJNI.Simulation_getStartingTeleportNumber();
  }

  public static StringVector getStartingTeleportIDList() {
    return new StringVector(libsumoJNI.Simulation_getStartingTeleportIDList(), true);
  }

  public static int getEndingTeleportNumber() {
    return libsumoJNI.Simulation_getEndingTeleportNumber();
  }

  public static StringVector getEndingTeleportIDList() {
    return new StringVector(libsumoJNI.Simulation_getEndingTeleportIDList(), true);
  }

  public static int getBusStopWaiting(String id) {
    return libsumoJNI.Simulation_getBusStopWaiting(id);
  }

  public static double getDeltaT() {
    return libsumoJNI.Simulation_getDeltaT();
  }

  public static SWIGTYPE_p_std__vectorT_libsumo__TraCIPosition_t getNetBoundary() {
    return new SWIGTYPE_p_std__vectorT_libsumo__TraCIPosition_t(libsumoJNI.Simulation_getNetBoundary(), true);
  }

  public static TraCIPosition convert2D(String edgeID, double pos, int laneIndex, boolean toGeo) {
    return new TraCIPosition(libsumoJNI.Simulation_convert2D__SWIG_0(edgeID, pos, laneIndex, toGeo), true);
  }

  public static TraCIPosition convert2D(String edgeID, double pos, int laneIndex) {
    return new TraCIPosition(libsumoJNI.Simulation_convert2D__SWIG_1(edgeID, pos, laneIndex), true);
  }

  public static TraCIPosition convert2D(String edgeID, double pos) {
    return new TraCIPosition(libsumoJNI.Simulation_convert2D__SWIG_2(edgeID, pos), true);
  }

  public static TraCIPosition convert3D(String edgeID, double pos, int laneIndex, boolean toGeo) {
    return new TraCIPosition(libsumoJNI.Simulation_convert3D__SWIG_0(edgeID, pos, laneIndex, toGeo), true);
  }

  public static TraCIPosition convert3D(String edgeID, double pos, int laneIndex) {
    return new TraCIPosition(libsumoJNI.Simulation_convert3D__SWIG_1(edgeID, pos, laneIndex), true);
  }

  public static TraCIPosition convert3D(String edgeID, double pos) {
    return new TraCIPosition(libsumoJNI.Simulation_convert3D__SWIG_2(edgeID, pos), true);
  }

  public static TraCIRoadPosition convertRoad(double x, double y, boolean isGeo) {
    return new TraCIRoadPosition(libsumoJNI.Simulation_convertRoad__SWIG_0(x, y, isGeo), true);
  }

  public static TraCIRoadPosition convertRoad(double x, double y) {
    return new TraCIRoadPosition(libsumoJNI.Simulation_convertRoad__SWIG_1(x, y), true);
  }

  public static TraCIPosition convertGeo(double x, double y, boolean fromGeo) {
    return new TraCIPosition(libsumoJNI.Simulation_convertGeo__SWIG_0(x, y, fromGeo), true);
  }

  public static TraCIPosition convertGeo(double x, double y) {
    return new TraCIPosition(libsumoJNI.Simulation_convertGeo__SWIG_1(x, y), true);
  }

  public static double getDistance2D(double x1, double y1, double x2, double y2, boolean isGeo, boolean isDriving) {
    return libsumoJNI.Simulation_getDistance2D__SWIG_0(x1, y1, x2, y2, isGeo, isDriving);
  }

  public static double getDistance2D(double x1, double y1, double x2, double y2, boolean isGeo) {
    return libsumoJNI.Simulation_getDistance2D__SWIG_1(x1, y1, x2, y2, isGeo);
  }

  public static double getDistance2D(double x1, double y1, double x2, double y2) {
    return libsumoJNI.Simulation_getDistance2D__SWIG_2(x1, y1, x2, y2);
  }

  public static double getDistanceRoad(String edgeID1, double pos1, String edgeID2, double pos2, boolean isDriving) {
    return libsumoJNI.Simulation_getDistanceRoad__SWIG_0(edgeID1, pos1, edgeID2, pos2, isDriving);
  }

  public static double getDistanceRoad(String edgeID1, double pos1, String edgeID2, double pos2) {
    return libsumoJNI.Simulation_getDistanceRoad__SWIG_1(edgeID1, pos1, edgeID2, pos2);
  }

  public static int getMinExpectedNumber() {
    return libsumoJNI.Simulation_getMinExpectedNumber();
  }

  public static TraCIStage findRoute(String fromEdge, String toEdge, String vType, double depart, int routingMode) {
    return new TraCIStage(libsumoJNI.Simulation_findRoute__SWIG_0(fromEdge, toEdge, vType, depart, routingMode), true);
  }

  public static TraCIStage findRoute(String fromEdge, String toEdge, String vType, double depart) {
    return new TraCIStage(libsumoJNI.Simulation_findRoute__SWIG_1(fromEdge, toEdge, vType, depart), true);
  }

  public static TraCIStage findRoute(String fromEdge, String toEdge, String vType) {
    return new TraCIStage(libsumoJNI.Simulation_findRoute__SWIG_2(fromEdge, toEdge, vType), true);
  }

  public static TraCIStage findRoute(String fromEdge, String toEdge) {
    return new TraCIStage(libsumoJNI.Simulation_findRoute__SWIG_3(fromEdge, toEdge), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed, double walkFactor, double departPos, double arrivalPos, double departPosLat, String pType, String vType, String destStop) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_0(fromEdge, toEdge, modes, depart, routingMode, speed, walkFactor, departPos, arrivalPos, departPosLat, pType, vType, destStop), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed, double walkFactor, double departPos, double arrivalPos, double departPosLat, String pType, String vType) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_1(fromEdge, toEdge, modes, depart, routingMode, speed, walkFactor, departPos, arrivalPos, departPosLat, pType, vType), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed, double walkFactor, double departPos, double arrivalPos, double departPosLat, String pType) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_2(fromEdge, toEdge, modes, depart, routingMode, speed, walkFactor, departPos, arrivalPos, departPosLat, pType), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed, double walkFactor, double departPos, double arrivalPos, double departPosLat) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_3(fromEdge, toEdge, modes, depart, routingMode, speed, walkFactor, departPos, arrivalPos, departPosLat), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed, double walkFactor, double departPos, double arrivalPos) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_4(fromEdge, toEdge, modes, depart, routingMode, speed, walkFactor, departPos, arrivalPos), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed, double walkFactor, double departPos) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_5(fromEdge, toEdge, modes, depart, routingMode, speed, walkFactor, departPos), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed, double walkFactor) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_6(fromEdge, toEdge, modes, depart, routingMode, speed, walkFactor), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode, double speed) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_7(fromEdge, toEdge, modes, depart, routingMode, speed), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart, int routingMode) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_8(fromEdge, toEdge, modes, depart, routingMode), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes, double depart) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_9(fromEdge, toEdge, modes, depart), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge, String modes) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_10(fromEdge, toEdge, modes), true);
  }

  public static TraCIStageVector findIntermodalRoute(String fromEdge, String toEdge) {
    return new TraCIStageVector(libsumoJNI.Simulation_findIntermodalRoute__SWIG_11(fromEdge, toEdge), true);
  }

  public static String getParameter(String objectID, String key) {
    return libsumoJNI.Simulation_getParameter(objectID, key);
  }

  public static void clearPending(String routeID) {
    libsumoJNI.Simulation_clearPending__SWIG_0(routeID);
  }

  public static void clearPending() {
    libsumoJNI.Simulation_clearPending__SWIG_1();
  }

  public static void saveState(String fileName) {
    libsumoJNI.Simulation_saveState(fileName);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.Simulation_subscribe__SWIG_0(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.Simulation_subscribe__SWIG_1(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.Simulation_subscribe__SWIG_2(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribe(String objID) {
    libsumoJNI.Simulation_subscribe__SWIG_3(objID);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.Simulation_subscribeContext__SWIG_0(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.Simulation_subscribeContext__SWIG_1(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.Simulation_subscribeContext__SWIG_2(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribeContext(String objID, int domain, double range) {
    libsumoJNI.Simulation_subscribeContext__SWIG_3(objID, domain, range);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getAllSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.Simulation_getAllSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t getSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t(libsumoJNI.Simulation_getSubscriptionResults__SWIG_0(objID), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t getAllContextSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t(libsumoJNI.Simulation_getAllContextSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getContextSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.Simulation_getContextSubscriptionResults(objID), true);
  }

  public static void subscribe(SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.Simulation_subscribe__SWIG_4(SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribe(SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.Simulation_subscribe__SWIG_5(SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribe(SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.Simulation_subscribe__SWIG_6(SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribe() {
    libsumoJNI.Simulation_subscribe__SWIG_7();
  }

  public static SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t getSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t(libsumoJNI.Simulation_getSubscriptionResults__SWIG_1(), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t makeWrapper() {
    return new SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t(libsumoJNI.Simulation_makeWrapper(), true);
  }

  public static boolean handleVariable(String objID, int variable, SWIGTYPE_p_libsumo__VariableWrapper wrapper) {
    return libsumoJNI.Simulation_handleVariable(objID, variable, SWIGTYPE_p_libsumo__VariableWrapper.getCPtr(wrapper));
  }

}
