/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class TraCIString extends TraCIResult {
  private transient long swigCPtr;

  protected TraCIString(long cPtr, boolean cMemoryOwn) {
    super(libsumoJNI.TraCIString_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TraCIString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_TraCIString(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TraCIString() {
    this(libsumoJNI.new_TraCIString__SWIG_0(), true);
  }

  public TraCIString(String v) {
    this(libsumoJNI.new_TraCIString__SWIG_1(v), true);
  }

  public String getString() {
    return libsumoJNI.TraCIString_getString(swigCPtr, this);
  }

  public void setValue(String value) {
    libsumoJNI.TraCIString_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return libsumoJNI.TraCIString_value_get(swigCPtr, this);
  }

}
