/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class TraCIPhase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TraCIPhase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TraCIPhase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_TraCIPhase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TraCIPhase() {
    this(libsumoJNI.new_TraCIPhase__SWIG_0(), true);
  }

  public TraCIPhase(double _duration, double _duration1, double _duration2, String _phase, int _next) {
    this(libsumoJNI.new_TraCIPhase__SWIG_1(_duration, _duration1, _duration2, _phase, _next), true);
  }

  public TraCIPhase(double _duration, double _duration1, double _duration2, String _phase) {
    this(libsumoJNI.new_TraCIPhase__SWIG_2(_duration, _duration1, _duration2, _phase), true);
  }

  public void setDuration(double value) {
    libsumoJNI.TraCIPhase_duration_set(swigCPtr, this, value);
  }

  public double getDuration() {
    return libsumoJNI.TraCIPhase_duration_get(swigCPtr, this);
  }

  public void setDuration1(double value) {
    libsumoJNI.TraCIPhase_duration1_set(swigCPtr, this, value);
  }

  public double getDuration1() {
    return libsumoJNI.TraCIPhase_duration1_get(swigCPtr, this);
  }

  public void setDuration2(double value) {
    libsumoJNI.TraCIPhase_duration2_set(swigCPtr, this, value);
  }

  public double getDuration2() {
    return libsumoJNI.TraCIPhase_duration2_get(swigCPtr, this);
  }

  public void setPhase(String value) {
    libsumoJNI.TraCIPhase_phase_set(swigCPtr, this, value);
  }

  public String getPhase() {
    return libsumoJNI.TraCIPhase_phase_get(swigCPtr, this);
  }

  public void setNext(int value) {
    libsumoJNI.TraCIPhase_next_set(swigCPtr, this, value);
  }

  public int getNext() {
    return libsumoJNI.TraCIPhase_next_get(swigCPtr, this);
  }

}
