/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class TraCIDouble extends TraCIResult {
  private transient long swigCPtr;

  protected TraCIDouble(long cPtr, boolean cMemoryOwn) {
    super(libsumoJNI.TraCIDouble_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TraCIDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_TraCIDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TraCIDouble() {
    this(libsumoJNI.new_TraCIDouble__SWIG_0(), true);
  }

  public TraCIDouble(double v) {
    this(libsumoJNI.new_TraCIDouble__SWIG_1(v), true);
  }

  public String getString() {
    return libsumoJNI.TraCIDouble_getString(swigCPtr, this);
  }

  public void setValue(double value) {
    libsumoJNI.TraCIDouble_value_set(swigCPtr, this, value);
  }

  public double getValue() {
    return libsumoJNI.TraCIDouble_value_get(swigCPtr, this);
  }

}
