/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class TraCIPhase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TraCIPhase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TraCIPhase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_TraCIPhase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TraCIPhase() {
    this(libsumoJNI.new_TraCIPhase__SWIG_0(), true);
  }

  public TraCIPhase(double _duration, String _state, double _minDur, double _maxDur, int _next) {
    this(libsumoJNI.new_TraCIPhase__SWIG_1(_duration, _state, _minDur, _maxDur, _next), true);
  }

  public TraCIPhase(double _duration, String _state, double _minDur, double _maxDur) {
    this(libsumoJNI.new_TraCIPhase__SWIG_2(_duration, _state, _minDur, _maxDur), true);
  }

  public TraCIPhase(double _duration, String _state, double _minDur) {
    this(libsumoJNI.new_TraCIPhase__SWIG_3(_duration, _state, _minDur), true);
  }

  public TraCIPhase(double _duration, String _state) {
    this(libsumoJNI.new_TraCIPhase__SWIG_4(_duration, _state), true);
  }

  public void setDuration(double value) {
    libsumoJNI.TraCIPhase_duration_set(swigCPtr, this, value);
  }

  public double getDuration() {
    return libsumoJNI.TraCIPhase_duration_get(swigCPtr, this);
  }

  public void setState(String value) {
    libsumoJNI.TraCIPhase_state_set(swigCPtr, this, value);
  }

  public String getState() {
    return libsumoJNI.TraCIPhase_state_get(swigCPtr, this);
  }

  public void setMinDur(double value) {
    libsumoJNI.TraCIPhase_minDur_set(swigCPtr, this, value);
  }

  public double getMinDur() {
    return libsumoJNI.TraCIPhase_minDur_get(swigCPtr, this);
  }

  public void setMaxDur(double value) {
    libsumoJNI.TraCIPhase_maxDur_set(swigCPtr, this, value);
  }

  public double getMaxDur() {
    return libsumoJNI.TraCIPhase_maxDur_get(swigCPtr, this);
  }

  public void setNext(int value) {
    libsumoJNI.TraCIPhase_next_set(swigCPtr, this, value);
  }

  public int getNext() {
    return libsumoJNI.TraCIPhase_next_get(swigCPtr, this);
  }

}
