/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.eclipse.sumo.libsumo;

public class TrafficLight {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TrafficLight(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TrafficLight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsumoJNI.delete_TrafficLight(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static StringVector getIDList() {
    return new StringVector(libsumoJNI.TrafficLight_getIDList(), true);
  }

  public static int getIDCount() {
    return libsumoJNI.TrafficLight_getIDCount();
  }

  public static String getRedYellowGreenState(String tlsID) {
    return libsumoJNI.TrafficLight_getRedYellowGreenState(tlsID);
  }

  public static TraCILogicVector getCompleteRedYellowGreenDefinition(String tlsID) {
    return new TraCILogicVector(libsumoJNI.TrafficLight_getCompleteRedYellowGreenDefinition(tlsID), true);
  }

  public static StringVector getControlledJunctions(String tlsID) {
    return new StringVector(libsumoJNI.TrafficLight_getControlledJunctions(tlsID), true);
  }

  public static StringVector getControlledLanes(String tlsID) {
    return new StringVector(libsumoJNI.TrafficLight_getControlledLanes(tlsID), true);
  }

  public static SWIGTYPE_p_std__vectorT_std__vectorT_libsumo__TraCILink_t_t getControlledLinks(String tlsID) {
    return new SWIGTYPE_p_std__vectorT_std__vectorT_libsumo__TraCILink_t_t(libsumoJNI.TrafficLight_getControlledLinks(tlsID), true);
  }

  public static String getProgram(String tlsID) {
    return libsumoJNI.TrafficLight_getProgram(tlsID);
  }

  public static int getPhase(String tlsID) {
    return libsumoJNI.TrafficLight_getPhase(tlsID);
  }

  public static double getPhaseDuration(String tlsID) {
    return libsumoJNI.TrafficLight_getPhaseDuration(tlsID);
  }

  public static double getNextSwitch(String tlsID) {
    return libsumoJNI.TrafficLight_getNextSwitch(tlsID);
  }

  public static String getParameter(String tlsID, String paramName) {
    return libsumoJNI.TrafficLight_getParameter(tlsID, paramName);
  }

  public static void setRedYellowGreenState(String tlsID, String state) {
    libsumoJNI.TrafficLight_setRedYellowGreenState(tlsID, state);
  }

  public static void setPhase(String tlsID, int index) {
    libsumoJNI.TrafficLight_setPhase(tlsID, index);
  }

  public static void setProgram(String tlsID, String programID) {
    libsumoJNI.TrafficLight_setProgram(tlsID, programID);
  }

  public static void setPhaseDuration(String tlsID, double phaseDuration) {
    libsumoJNI.TrafficLight_setPhaseDuration(tlsID, phaseDuration);
  }

  public static void setCompleteRedYellowGreenDefinition(String tlsID, TraCILogic logic) {
    libsumoJNI.TrafficLight_setCompleteRedYellowGreenDefinition(tlsID, TraCILogic.getCPtr(logic), logic);
  }

  public static void setParameter(String tlsID, String paramName, String value) {
    libsumoJNI.TrafficLight_setParameter(tlsID, paramName, value);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.TrafficLight_subscribe__SWIG_0(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.TrafficLight_subscribe__SWIG_1(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribe(String objID, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.TrafficLight_subscribe__SWIG_2(objID, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribe(String objID) {
    libsumoJNI.TrafficLight_subscribe__SWIG_3(objID);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime, double endTime) {
    libsumoJNI.TrafficLight_subscribeContext__SWIG_0(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime, endTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars, double beginTime) {
    libsumoJNI.TrafficLight_subscribeContext__SWIG_1(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars), beginTime);
  }

  public static void subscribeContext(String objID, int domain, double range, SWIGTYPE_p_std__vectorT_int_t vars) {
    libsumoJNI.TrafficLight_subscribeContext__SWIG_2(objID, domain, range, SWIGTYPE_p_std__vectorT_int_t.getCPtr(vars));
  }

  public static void subscribeContext(String objID, int domain, double range) {
    libsumoJNI.TrafficLight_subscribeContext__SWIG_3(objID, domain, range);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getAllSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.TrafficLight_getAllSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t getSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t(libsumoJNI.TrafficLight_getSubscriptionResults(objID), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t getAllContextSubscriptionResults() {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t_t(libsumoJNI.TrafficLight_getAllContextSubscriptionResults(), true);
  }

  public static SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t getContextSubscriptionResults(String objID) {
    return new SWIGTYPE_p_std__mapT_std__string_std__mapT_int_std__shared_ptrT_libsumo__TraCIResult_t_t_t(libsumoJNI.TrafficLight_getContextSubscriptionResults(objID), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t makeWrapper() {
    return new SWIGTYPE_p_std__shared_ptrT_libsumo__VariableWrapper_t(libsumoJNI.TrafficLight_makeWrapper(), true);
  }

  public static boolean handleVariable(String objID, int variable, SWIGTYPE_p_libsumo__VariableWrapper wrapper) {
    return libsumoJNI.TrafficLight_handleVariable(objID, variable, SWIGTYPE_p_libsumo__VariableWrapper.getCPtr(wrapper));
  }

}
